---
title: 'Exceptions : invalidArg (fonction)'
description: Découvrez comment la F# « invalidArg » fonction génère une exception d’argument.
ms.date: 05/16/2016
ms.openlocfilehash: 1f0cbc9b7e805822544d6d54bc1fc69adf82967a
ms.sourcegitcommit: 8699383914c24a0df033393f55db3369db728a7b
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 05/15/2019
ms.locfileid: "65645499"
---
# <a name="exceptions-the-invalidarg-function"></a><span data-ttu-id="ddcc2-103">Exceptions : invalidArg (fonction)</span><span class="sxs-lookup"><span data-stu-id="ddcc2-103">Exceptions: The invalidArg Function</span></span>

<span data-ttu-id="ddcc2-104">Le `invalidArg` fonction génère une exception d’argument.</span><span class="sxs-lookup"><span data-stu-id="ddcc2-104">The `invalidArg` function generates an argument exception.</span></span>

## <a name="syntax"></a><span data-ttu-id="ddcc2-105">Syntaxe</span><span class="sxs-lookup"><span data-stu-id="ddcc2-105">Syntax</span></span>

```fsharp
invalidArg parameter-name error-message-string
```

## <a name="remarks"></a><span data-ttu-id="ddcc2-106">Notes</span><span class="sxs-lookup"><span data-stu-id="ddcc2-106">Remarks</span></span>

<span data-ttu-id="ddcc2-107">Le nom de paramètre dans la syntaxe précédente est une chaîne avec le nom du paramètre dont l’argument n’est pas valide.</span><span class="sxs-lookup"><span data-stu-id="ddcc2-107">The parameter-name in the previous syntax is a string with the name of the parameter whose argument was invalid.</span></span> <span data-ttu-id="ddcc2-108">Le *chaîne du message d’erreur* est une chaîne littérale ou une valeur de type `string`.</span><span class="sxs-lookup"><span data-stu-id="ddcc2-108">The *error-message-string* is a literal string or a value of type `string`.</span></span> <span data-ttu-id="ddcc2-109">Il devient le `Message` propriété de l’objet exception.</span><span class="sxs-lookup"><span data-stu-id="ddcc2-109">It becomes the `Message` property of the exception object.</span></span>

<span data-ttu-id="ddcc2-110">L’exception générée par `invalidArg` est un `System.ArgumentException` exception.</span><span class="sxs-lookup"><span data-stu-id="ddcc2-110">The exception generated by `invalidArg` is a `System.ArgumentException` exception.</span></span> <span data-ttu-id="ddcc2-111">Le code suivant illustre l’utilisation de `invalidArg` pour lever une exception.</span><span class="sxs-lookup"><span data-stu-id="ddcc2-111">The following code illustrates the use of `invalidArg` to throw an exception.</span></span>

[!code-fsharp[Main](../../../../samples/snippets/fsharp/lang-ref-2/snippet6101.fs)]

<span data-ttu-id="ddcc2-112">La sortie est la suivante, suivie d’une trace de pile (non illustrée).</span><span class="sxs-lookup"><span data-stu-id="ddcc2-112">The output is the following, followed by a stack trace (not shown).</span></span>

```
December
January
System.ArgumentException: Month parameter out of range.
```

## <a name="see-also"></a><span data-ttu-id="ddcc2-113">Voir aussi</span><span class="sxs-lookup"><span data-stu-id="ddcc2-113">See also</span></span>

- [<span data-ttu-id="ddcc2-114">Gestion des exceptions</span><span class="sxs-lookup"><span data-stu-id="ddcc2-114">Exception Handling</span></span>](index.md)
- [<span data-ttu-id="ddcc2-115">Types d'exceptions</span><span class="sxs-lookup"><span data-stu-id="ddcc2-115">Exception Types</span></span>](exception-types.md)
- [<span data-ttu-id="ddcc2-116">Exceptions : Le `try...with` Expression</span><span class="sxs-lookup"><span data-stu-id="ddcc2-116">Exceptions: The `try...with` Expression</span></span>](the-try-with-expression.md)
- [<span data-ttu-id="ddcc2-117">Exceptions : Le `try...finally` Expression</span><span class="sxs-lookup"><span data-stu-id="ddcc2-117">Exceptions: The `try...finally` Expression</span></span>](the-try-finally-expression.md)
- [<span data-ttu-id="ddcc2-118">Exceptions : fonction `raise`</span><span class="sxs-lookup"><span data-stu-id="ddcc2-118">Exceptions: the `raise` Function</span></span>](the-raise-function.md)
- [<span data-ttu-id="ddcc2-119">Exceptions : Le `failwith` (fonction)</span><span class="sxs-lookup"><span data-stu-id="ddcc2-119">Exceptions: The `failwith` Function</span></span>](the-failwith-function.md)
